[tools]
"cargo:cargo-audit" = "0.22.2"
"cargo:cargo-fuzz" = "0.13.2"
"cargo:cargo-watch" = "8.5.3"
"cargo:dioxus-cli" = "0.7.10"
"github:nextest-rs/nextest" = "cargo-nextest-0.9.143"
helm = "4.2.4"
kubectl = "1.37.0"
semgrep = "1.175.0"
trivy = "0.74.0"
