//! The basemap of the Statistics page's heat map: country outlines and
//! populated places from Natural Earth, generated by `just places` into
//! `assets/basemap/countries.json.br` (see `docs/ui-statistics.md`).

use std::sync::OnceLock;

use serde::{Deserialize, Serialize};

use crate::embedded;

static BASEMAP: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../assets/basemap/countries.json.br"
));

/// One country's outline and populated places.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "graphql", derive(async_graphql::SimpleObject))]
pub struct BasemapCountry {
    /// ISO 3166-1 alpha-2 code, `-99` where Natural Earth has none.
    pub iso: String,
    pub name: String,
    /// Outer rings, each a flat list of `longitude, latitude` pairs in tenths
    /// of a degree.
    pub rings: Vec<Vec<i32>>,
    /// Populated places, by the zoom they are labelled from, then the most
    /// populated first.
    pub cities: Vec<BasemapCity>,
}

/// A populated place, labelled on the map from a zoom on.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "graphql", derive(async_graphql::SimpleObject))]
pub struct BasemapCity {
    pub name: String,
    /// Its names in the interface languages, where they differ.
    pub names: Vec<LocalName>,
    /// Longitude and latitude in tenths of a degree.
    pub lon: i32,
    pub lat: i32,
    /// The web map zoom level it is labelled from, in tenths (Natural
    /// Earth's `MIN_ZOOM`).
    pub zoom: i32,
    /// In thousands.
    pub population: i64,
}

/// A name in one interface language.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "graphql", derive(async_graphql::SimpleObject))]
pub struct LocalName {
    pub lang: String,
    pub name: String,
}

/// A strong validator of the base map: a digest of the embedded data, which
/// only a new build changes.
pub fn basemap_etag() -> &'static str {
    use sha2::{Digest as _, Sha256};
    static ETAG: OnceLock<String> = OnceLock::new();
    ETAG.get_or_init(|| {
        let digest = Sha256::digest(BASEMAP);
        let hex: String = digest[..16].iter().map(|b| format!("{b:02x}")).collect();
        format!("\"{hex}\"")
    })
}

/// Every country's outline, decompressed once.
pub fn basemap() -> &'static [BasemapCountry] {
    static COUNTRIES: OnceLock<Vec<BasemapCountry>> = OnceLock::new();
    COUNTRIES.get_or_init(|| {
        serde_json::from_slice(&embedded::decompress(BASEMAP))
            .expect("the embedded basemap must be valid JSON")
    })
}

#[cfg(test)]
mod tests {
    use super::basemap;

    #[test]
    fn the_embedded_basemap_loads() {
        let countries = basemap();
        assert!(countries.len() > 200);
        let france = countries
            .iter()
            .find(|c| c.iso == "FR" && !c.rings.is_empty())
            .expect("France has an outline");
        // Its places come by zoom: the capital is labelled first.
        assert!(france.cities.len() > 10);
        assert!(france.cities.windows(2).all(|w| w[0].zoom <= w[1].zoom));
        assert!(france.cities[0].zoom < 30);
    }
}
