//! The basemap of the Statistics page's heat map: country outlines from
//! Natural Earth, generated by `just places` into
//! `assets/basemap/countries.json.br` (see `docs/ui-statistics.md`).

use std::sync::OnceLock;

use serde::{Deserialize, Serialize};

use crate::embedded;

static BASEMAP: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../assets/basemap/countries.json.br"
));

/// One country's outline.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "graphql", derive(async_graphql::SimpleObject))]
pub struct BasemapCountry {
    /// ISO 3166-1 alpha-2 code, `-99` where Natural Earth has none.
    pub iso: String,
    pub name: String,
    /// Outer rings, each a flat list of `longitude, latitude` pairs in tenths
    /// of a degree.
    pub rings: Vec<Vec<i32>>,
}

/// Every country's outline, decompressed once.
pub fn basemap() -> &'static [BasemapCountry] {
    static COUNTRIES: OnceLock<Vec<BasemapCountry>> = OnceLock::new();
    COUNTRIES.get_or_init(|| {
        serde_json::from_slice(&embedded::decompress(BASEMAP))
            .expect("the embedded basemap must be valid JSON")
    })
}

#[cfg(test)]
mod tests {
    use super::basemap;

    #[test]
    fn the_embedded_basemap_loads() {
        let countries = basemap();
        assert!(countries.len() > 200);
        assert!(
            countries
                .iter()
                .any(|c| c.iso == "FR" && !c.rings.is_empty())
        );
    }
}
