//! The place dictionary: the France and United Kingdom places generated by
//! `just places` into `assets/places/places.csv.br` (see
//! `docs/place-dictionary.md`), searched to suggest place names.
//!
//! The file is decompressed and indexed on the first search, not at startup:
//! it holds 185,000 rows, and a session that never edits a place never pays
//! for them.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Serialize;

use super::loader::{ReferenceLang, normalize_key};
use crate::embedded;

static PLACES: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../assets/places/places.csv.br"
));

/// Suggestions returned when the caller names no limit.
pub const DEFAULT_PLACE_SUGGESTIONS: usize = 10;
/// The most suggestions one search returns.
pub const MAX_PLACE_SUGGESTIONS: usize = 50;

/// What a dictionary row is. The order is the order suggestions are
/// ranked in when their names match equally well.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum PlaceKind {
    Commune,
    MunicipalArrondissement,
    Settlement,
    Parish,
    FormerName,
    FormerCommune,
}

impl PlaceKind {
    fn parse(token: &str) -> Option<Self> {
        Some(match token {
            "commune" => Self::Commune,
            "municipal_arrondissement" => Self::MunicipalArrondissement,
            "settlement" => Self::Settlement,
            "parish" => Self::Parish,
            "former_name" => Self::FormerName,
            "former_commune" => Self::FormerCommune,
            _ => return None,
        })
    }
}

/// One suggested place, with the parts its label is made of.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct PlaceSuggestion {
    /// The place written the way a genealogy records it: its name, code,
    /// subdivision, region and country, most specific first.
    pub label: String,
    pub name: String,
    /// The INSEE commune code in France.
    pub code: Option<String>,
    pub subdivision: String,
    pub region: String,
    pub country: String,
    pub kind: PlaceKind,
    pub valid_from: Option<String>,
    pub valid_until: Option<String>,
    /// INSEE code of the commune holding a former commune's territory today.
    pub successor: Option<String>,
    pub latitude: Option<f64>,
    pub longitude: Option<f64>,
    /// Filed under today's subdivision and region rather than a former one.
    pub current: bool,
}

/// Searches the place dictionary.
///
/// The text before the first comma is matched against place names: an exact
/// name first, then names starting with it, then names with a word starting
/// with it. Each part after a comma must start a word of the code,
/// subdivision, region or country, so "Name, Subdivision" narrows the list.
/// Case, accents and punctuation are ignored.
pub fn search_places(lang: ReferenceLang, query: &str, limit: usize) -> Vec<PlaceSuggestion> {
    dictionary().search(lang, query, limit)
}

fn dictionary() -> &'static Dictionary {
    static DICTIONARY: OnceLock<Dictionary> = OnceLock::new();
    DICTIONARY.get_or_init(|| {
        let text = String::from_utf8(embedded::decompress(PLACES))
            .expect("the embedded place dictionary must be UTF-8");
        Dictionary::parse(&text)
    })
}

/// Names written in French in the file that the English interface names
/// otherwise.
fn english(french: &str) -> Option<&'static str> {
    Some(match french {
        "Royaume-Uni" => "United Kingdom",
        "Angleterre" => "England",
        "Écosse" => "Scotland",
        "Pays de Galles" => "Wales",
        "Irlande du Nord" => "Northern Ireland",
        _ => return None,
    })
}

/// A string stored in `Dictionary::text`.
#[derive(Clone, Copy)]
struct Span {
    start: u32,
    len: u32,
}

/// One row, in about 60 bytes: every string lives in one shared buffer, and
/// the few hundred subdivisions, regions and countries are stored once.
struct Entry {
    name: Span,
    folded: Span,
    code: Span,
    successor: Span,
    /// Indexes into `Dictionary::parts`.
    subdivision: u16,
    region: u16,
    country: u16,
    kind: PlaceKind,
    current: bool,
    /// `YYYYMMDD`, 0 when unknown.
    valid_from: u32,
    valid_until: u32,
    /// NaN when unknown.
    latitude: f32,
    longitude: f32,
}

/// A subdivision, region or country name. There are a few hundred, shared by
/// every row.
struct Part {
    text: [Box<str>; 2],
    folded: [String; 2],
}

impl Part {
    fn new(french: &str) -> Self {
        let english = english(french).unwrap_or(french);
        Self {
            text: [french.into(), english.into()],
            folded: [normalize_key(french), normalize_key(english)],
        }
    }
}

fn slot(lang: ReferenceLang) -> usize {
    match lang {
        ReferenceLang::Fr => 0,
        ReferenceLang::En => 1,
    }
}

/// `YYYY-MM-DD` as `YYYYMMDD`, 0 when empty.
fn pack_date(date: &str) -> u32 {
    date.bytes()
        .filter(u8::is_ascii_digit)
        .fold(0, |packed, digit| packed * 10 + u32::from(digit - b'0'))
}

fn unpack_date(packed: u32) -> Option<String> {
    (packed != 0).then(|| {
        format!(
            "{:04}-{:02}-{:02}",
            packed / 10_000,
            packed / 100 % 100,
            packed % 100
        )
    })
}

struct Dictionary {
    entries: Vec<Entry>,
    text: String,
    parts: Vec<Part>,
}

impl Dictionary {
    fn parse(csv: &str) -> Self {
        let mut text = String::new();
        let mut store = |value: &str| {
            let span = Span {
                start: u32::try_from(text.len()).expect("the dictionary text fits in 4 GiB"),
                len: u32::try_from(value.len()).expect("a field fits in 4 GiB"),
            };
            text.push_str(value);
            span
        };
        let mut parts = Vec::new();
        let mut interned: HashMap<String, u16> = HashMap::new();
        let mut intern = |value: &str| -> u16 {
            *interned.entry(value.to_string()).or_insert_with(|| {
                parts.push(Part::new(value));
                u16::try_from(parts.len() - 1).expect("fewer than 65,536 place parts")
            })
        };
        let mut entries = Vec::new();
        for line in csv.lines().filter(|l| !l.is_empty()) {
            let fields = split_quoted(line);
            let [
                name,
                code,
                subdivision,
                region,
                country,
                kind,
                from,
                until,
                successor,
                lat,
                lon,
                current,
            ] = fields.as_slice()
            else {
                panic!("the embedded place dictionary has a malformed row: {line}");
            };
            let kind = PlaceKind::parse(kind)
                .unwrap_or_else(|| panic!("unknown place kind `{kind}` in the dictionary"));
            let coordinate = |value: &str| value.parse().unwrap_or(f32::NAN);
            entries.push(Entry {
                name: store(name),
                folded: store(&normalize_key(name)),
                code: store(code),
                successor: store(successor),
                subdivision: intern(subdivision),
                region: intern(region),
                country: intern(country),
                kind,
                current: current == "1",
                valid_from: pack_date(from),
                valid_until: pack_date(until),
                latitude: coordinate(lat),
                longitude: coordinate(lon),
            });
        }
        text.shrink_to_fit();
        entries.shrink_to_fit();
        Self {
            entries,
            text,
            parts,
        }
    }

    fn get(&self, span: Span) -> &str {
        let start = span.start as usize;
        &self.text[start..start + span.len as usize]
    }

    fn search(&self, lang: ReferenceLang, query: &str, limit: usize) -> Vec<PlaceSuggestion> {
        let mut pieces = query.split(',');
        let name = normalize_key(pieces.next().unwrap_or_default());
        let qualifiers: Vec<String> = pieces
            .map(normalize_key)
            .filter(|q| !q.is_empty())
            .collect();
        if name.is_empty() || limit == 0 {
            return Vec::new();
        }
        let lang = slot(lang);
        let mut matches: Vec<(u8, &Entry)> = self
            .entries
            .iter()
            .filter_map(|entry| Some((name_rank(self.get(entry.folded), &name)?, entry)))
            .filter(|(_, entry)| {
                qualifiers.iter().all(|qualifier| {
                    let code = self.get(entry.code);
                    code.get(..qualifier.len())
                        .is_some_and(|head| head.eq_ignore_ascii_case(qualifier))
                        || [entry.subdivision, entry.region, entry.country]
                            .iter()
                            .any(|&part| {
                                starts_a_word(
                                    &self.parts[usize::from(part)].folded[lang],
                                    qualifier,
                                )
                            })
                })
            })
            .collect();
        matches.sort_by(|(rank_a, a), (rank_b, b)| {
            let key = |rank, entry: &Entry| {
                let name = self.get(entry.name);
                (rank, !entry.current, entry.kind, name.len(), name)
            };
            key(rank_a, a).cmp(&key(rank_b, b))
        });
        matches
            .into_iter()
            .take(limit)
            .map(|(_, entry)| self.suggestion(entry, lang))
            .collect()
    }

    fn suggestion(&self, entry: &Entry, lang: usize) -> PlaceSuggestion {
        let part = |index: u16| self.parts[usize::from(index)].text[lang].to_string();
        let (name, code) = (self.get(entry.name), self.get(entry.code));
        let (subdivision, region, country) = (
            part(entry.subdivision),
            part(entry.region),
            part(entry.country),
        );
        let label = [name, code, &subdivision, &region, &country]
            .into_iter()
            .filter(|p| !p.is_empty())
            .collect::<Vec<_>>()
            .join(", ");
        let optional = |value: &str| (!value.is_empty()).then(|| value.to_string());
        let coordinate = |value: f32| (!value.is_nan()).then_some(f64::from(value));
        PlaceSuggestion {
            label,
            name: name.to_string(),
            code: optional(code),
            subdivision,
            region,
            country,
            kind: entry.kind,
            valid_from: unpack_date(entry.valid_from),
            valid_until: unpack_date(entry.valid_until),
            successor: optional(self.get(entry.successor)),
            latitude: coordinate(entry.latitude),
            longitude: coordinate(entry.longitude),
            current: entry.current,
        }
    }
}

/// 0 for the same name, 1 for a name starting with the query, 2 for a name
/// with a later word starting with it.
fn name_rank(name: &str, query: &str) -> Option<u8> {
    if name == query {
        Some(0)
    } else if name.starts_with(query) {
        Some(1)
    } else if starts_a_word(name, query) {
        Some(2)
    } else {
        None
    }
}

/// Whether `query` appears in `text` at the start of a word.
fn starts_a_word(text: &str, query: &str) -> bool {
    text.match_indices(query)
        .any(|(at, _)| at == 0 || text.as_bytes()[at - 1] == b' ')
}

/// Splits a row of quoted fields, as the generator writes them.
fn split_quoted(line: &str) -> Vec<String> {
    let mut fields = Vec::new();
    let mut field = String::new();
    let mut quoted = false;
    let mut chars = line.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '"' if quoted && chars.peek() == Some(&'"') => {
                field.push('"');
                chars.next();
            }
            '"' => quoted = !quoted,
            ',' if !quoted => fields.push(std::mem::take(&mut field)),
            _ => field.push(c),
        }
    }
    fields.push(field);
    fields
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A fictitious dictionary: a commune under its current and former
    /// département names, two homonyms, and a British hamlet.
    const ROWS: &str = r#""Bourg-A","99001","Département A","Région A","France","commune","","","","48.1","-1.5","1"
"Bourg-A","99001","Ancien Département A","Région A","France","commune","","","","48.1","-1.5",""
"Bourg-Ancien","99002","Département A","Région A","France","former_commune","","1960-01-01","99001","","",""
"Le Bourg-A","99003","Département B","Région A","France","commune","","","","","","1"
"Hamlet A","","Shire A","Angleterre","Royaume-Uni","settlement","","","","52.0","-1.0","1"
"#;

    fn names(suggestions: &[PlaceSuggestion]) -> Vec<(&str, &str)> {
        suggestions
            .iter()
            .map(|s| (s.name.as_str(), s.subdivision.as_str()))
            .collect()
    }

    #[test]
    fn exact_names_come_first_then_prefixes_then_later_words() {
        let dictionary = Dictionary::parse(ROWS);
        let found = dictionary.search(ReferenceLang::Fr, "bourg a", 10);
        assert_eq!(
            names(&found),
            [
                ("Bourg-A", "Département A"),
                ("Bourg-A", "Ancien Département A"),
                ("Bourg-Ancien", "Département A"),
                ("Le Bourg-A", "Département B"),
            ]
        );
    }

    #[test]
    fn a_suggestion_carries_its_label_and_its_parts() {
        let dictionary = Dictionary::parse(ROWS);
        let found = dictionary.search(ReferenceLang::Fr, "Bourg-Ancien", 1);
        assert_eq!(
            found[0],
            PlaceSuggestion {
                label: "Bourg-Ancien, 99002, Département A, Région A, France".to_string(),
                name: "Bourg-Ancien".to_string(),
                code: Some("99002".to_string()),
                subdivision: "Département A".to_string(),
                region: "Région A".to_string(),
                country: "France".to_string(),
                kind: PlaceKind::FormerCommune,
                valid_from: None,
                valid_until: Some("1960-01-01".to_string()),
                successor: Some("99001".to_string()),
                latitude: None,
                longitude: None,
                current: false,
            }
        );
    }

    #[test]
    fn parts_after_a_comma_narrow_the_list() {
        let dictionary = Dictionary::parse(ROWS);
        let found = dictionary.search(ReferenceLang::Fr, "bourg, ancien dep", 10);
        assert_eq!(names(&found), [("Bourg-A", "Ancien Département A")]);
        let found = dictionary.search(ReferenceLang::Fr, "bourg, 99003", 10);
        assert_eq!(names(&found), [("Le Bourg-A", "Département B")]);
    }

    #[test]
    fn the_english_interface_names_british_nations_in_english() {
        let dictionary = Dictionary::parse(ROWS);
        let found = dictionary.search(ReferenceLang::En, "hamlet, england", 10);
        assert_eq!(found[0].label, "Hamlet A, Shire A, England, United Kingdom");
        let found = dictionary.search(ReferenceLang::Fr, "hamlet", 10);
        assert_eq!(found[0].label, "Hamlet A, Shire A, Angleterre, Royaume-Uni");
    }

    #[test]
    fn nothing_is_suggested_for_an_empty_name_or_limit() {
        let dictionary = Dictionary::parse(ROWS);
        assert!(
            dictionary
                .search(ReferenceLang::Fr, " , Région A", 10)
                .is_empty()
        );
        assert!(dictionary.search(ReferenceLang::Fr, "bourg", 0).is_empty());
        assert!(dictionary.search(ReferenceLang::Fr, "ourg", 10).is_empty());
    }

    #[test]
    fn dates_survive_packing() {
        assert_eq!(
            unpack_date(pack_date("1790-01-01")).as_deref(),
            Some("1790-01-01")
        );
        assert_eq!(unpack_date(pack_date("")), None);
    }

    #[test]
    fn the_embedded_dictionary_loads() {
        // Every row must parse; a malformed one panics while loading.
        assert!(dictionary().entries.len() > 100_000);
    }
}
