//! The place dictionary: the places generated by
//! `just places` into `assets/places/places.csv.br` (see
//! `docs/place-dictionary.md`), searched to suggest place names.
//!
//! The file is decompressed and indexed on the first search, not at startup:
//! it holds about 285,000 rows, and a session that never edits a place never pays
//! for them. Locating a tree's places for the statistics reuses that index
//! when a search has built it, and otherwise reads the file once for the
//! rows named like the tree's places, keeping nothing afterwards
//! ([`locate_places`]).

use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

use serde::Serialize;

use super::loader::{ReferenceLang, normalize_key, starts_a_word};
use crate::embedded;

static PLACES: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../assets/places/places.csv.br"
));

/// Suggestions returned when the caller names no limit.
pub const DEFAULT_PLACE_SUGGESTIONS: usize = 10;
/// The most suggestions one search returns.
pub const MAX_PLACE_SUGGESTIONS: usize = 50;

/// What a dictionary row is. The order is the order suggestions are
/// ranked in when their names match equally well.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum PlaceKind {
    Commune,
    MunicipalArrondissement,
    Settlement,
    Parish,
    FormerName,
    FormerCommune,
}

impl PlaceKind {
    fn parse(token: &str) -> Option<Self> {
        Some(match token {
            "commune" => Self::Commune,
            "municipal_arrondissement" => Self::MunicipalArrondissement,
            "settlement" => Self::Settlement,
            "parish" => Self::Parish,
            "former_name" => Self::FormerName,
            "former_commune" => Self::FormerCommune,
            _ => return None,
        })
    }
}

/// One suggested place, with the parts its label is made of.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct PlaceSuggestion {
    /// The place written the way a genealogy records it: its name, code,
    /// subdivision, region and country, most specific first.
    pub label: String,
    pub name: String,
    /// The INSEE commune code in France.
    pub code: Option<String>,
    pub subdivision: String,
    pub region: String,
    pub country: String,
    pub kind: PlaceKind,
    pub valid_from: Option<String>,
    pub valid_until: Option<String>,
    /// INSEE code of the commune holding a former commune's territory today.
    pub successor: Option<String>,
    pub latitude: Option<f64>,
    pub longitude: Option<f64>,
    /// Filed under today's subdivision and region rather than a former one.
    pub current: bool,
}

/// Searches the place dictionary.
///
/// The text before the first comma is matched against place names: an exact
/// name first, then names starting with it, then names with a word starting
/// with it. Each part after a comma must start a word of the code,
/// subdivision, region or country, so "Name, Subdivision" narrows the list.
/// Case, accents and punctuation are ignored.
pub fn search_places(lang: ReferenceLang, query: &str, limit: usize) -> Vec<PlaceSuggestion> {
    dictionary().search(lang, query, limit)
}

/// Where the place dictionary puts one of a tree's places: its spot, and
/// the country, region and subdivision it lies in, named in the requested
/// language. Any of them may be unknown.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct PlaceLocation {
    pub spot: Option<(f64, f64)>,
    pub country: Option<String>,
    pub region: Option<String>,
    pub subdivision: Option<String>,
}

/// Locates the places of a tree, with how often the tree uses each, in the
/// place dictionary (see `Dictionary::locate_all`).
///
/// The index place searches build is reused when it is in memory. Otherwise
/// the dictionary is decompressed and read once for the rows named like
/// the tree's places (a few thousand of 285,000), and dropped with them:
/// about a quarter of a second in a release build, and nothing held in
/// memory afterwards, where building the whole index would take three
/// times as long and keep a few tens of megabytes for the session.
pub fn locate_places(lang: ReferenceLang, labels: &[(&str, i64)]) -> Vec<PlaceLocation> {
    match DICTIONARY.get() {
        Some(dictionary) => dictionary.locate_all(labels, lang),
        None => Dictionary::for_labels(&decompressed(), labels).locate_all(labels, lang),
    }
}

/// A label read against the dictionary.
enum Located<'a> {
    At(&'a Entry),
    Among(Vec<&'a Entry>),
    Nowhere,
}

fn spot(entry: &Entry) -> (f64, f64) {
    (f64::from(entry.latitude), f64::from(entry.longitude))
}

/// The spot of places all within a fifth of a degree of the first.
fn clustered(entries: &[&Entry]) -> Option<(f64, f64)> {
    let first = spot(entries.first()?);
    entries
        .iter()
        .all(|e| {
            let (latitude, longitude) = spot(e);
            (latitude - first.0).abs() < 0.2 && (longitude - first.1).abs() < 0.2
        })
        .then_some(first)
}

/// Living places before former ones when a bare name is read.
fn kind_rank(kind: PlaceKind) -> u8 {
    match kind {
        PlaceKind::Commune | PlaceKind::MunicipalArrondissement => 0,
        PlaceKind::Settlement | PlaceKind::Parish => 1,
        PlaceKind::FormerCommune | PlaceKind::FormerName => 2,
    }
}

/// The whole dictionary, indexed for place searches on first use and kept.
static DICTIONARY: OnceLock<Dictionary> = OnceLock::new();

fn dictionary() -> &'static Dictionary {
    DICTIONARY.get_or_init(|| Dictionary::parse(&decompressed()))
}

fn decompressed() -> String {
    String::from_utf8(embedded::decompress(PLACES))
        .expect("the embedded place dictionary must be UTF-8")
}

/// The country and British nation names, written in French in the file, in
/// each interface language, in the order of [`ReferenceLang::ALL`] (the French
/// first). Subdivisions and regions keep their local official names.
const NAMES: &[[&str; 8]] = &[
    [
        "France",
        "France",
        "Frankreich",
        "Francia",
        "Francia",
        "Frankrijk",
        "Francja",
        "França",
    ],
    [
        "Royaume-Uni",
        "United Kingdom",
        "Vereinigtes Königreich",
        "Reino Unido",
        "Regno Unito",
        "Verenigd Koninkrijk",
        "Wielka Brytania",
        "Reino Unido",
    ],
    [
        "Angleterre",
        "England",
        "England",
        "Inglaterra",
        "Inghilterra",
        "Engeland",
        "Anglia",
        "Inglaterra",
    ],
    [
        "Écosse",
        "Scotland",
        "Schottland",
        "Escocia",
        "Scozia",
        "Schotland",
        "Szkocja",
        "Escócia",
    ],
    [
        "Pays de Galles",
        "Wales",
        "Wales",
        "Gales",
        "Galles",
        "Wales",
        "Walia",
        "País de Gales",
    ],
    [
        "Irlande du Nord",
        "Northern Ireland",
        "Nordirland",
        "Irlanda del Norte",
        "Irlanda del Nord",
        "Noord-Ierland",
        "Irlandia Północna",
        "Irlanda do Norte",
    ],
    [
        "Allemagne",
        "Germany",
        "Deutschland",
        "Alemania",
        "Germania",
        "Duitsland",
        "Niemcy",
        "Alemanha",
    ],
    [
        "Italie", "Italy", "Italien", "Italia", "Italia", "Italië", "Włochy", "Itália",
    ],
    [
        "Espagne",
        "Spain",
        "Spanien",
        "España",
        "Spagna",
        "Spanje",
        "Hiszpania",
        "Espanha",
    ],
    [
        "Suisse",
        "Switzerland",
        "Schweiz",
        "Suiza",
        "Svizzera",
        "Zwitserland",
        "Szwajcaria",
        "Suíça",
    ],
    [
        "Pologne", "Poland", "Polen", "Polonia", "Polonia", "Polen", "Polska", "Polónia",
    ],
    [
        "Etats-Unis d'Amérique",
        "United States",
        "Vereinigte Staaten",
        "Estados Unidos",
        "Stati Uniti",
        "Verenigde Staten",
        "Stany Zjednoczone",
        "Estados Unidos",
    ],
    [
        "Portugal",
        "Portugal",
        "Portugal",
        "Portugal",
        "Portogallo",
        "Portugal",
        "Portugalia",
        "Portugal",
    ],
    [
        "Belgique", "Belgium", "Belgien", "Bélgica", "Belgio", "België", "Belgia", "Bélgica",
    ],
    [
        "Luxembourg",
        "Luxembourg",
        "Luxemburg",
        "Luxemburgo",
        "Lussemburgo",
        "Luxemburg",
        "Luksemburg",
        "Luxemburgo",
    ],
    [
        "Pays-Bas",
        "Netherlands",
        "Niederlande",
        "Países Bajos",
        "Paesi Bassi",
        "Nederland",
        "Holandia",
        "Países Baixos",
    ],
];

/// A string stored in `Dictionary::text`.
#[derive(Clone, Copy)]
struct Span {
    start: u32,
    len: u32,
}

/// One row, in about 60 bytes: every string lives in one shared buffer, and
/// the few hundred subdivisions, regions and countries are stored once.
struct Entry {
    name: Span,
    folded: Span,
    code: Span,
    successor: Span,
    /// Indexes into `Dictionary::parts`.
    subdivision: u16,
    region: u16,
    country: u16,
    kind: PlaceKind,
    current: bool,
    /// `YYYYMMDD`, 0 when unknown.
    valid_from: u32,
    valid_until: u32,
    /// NaN when unknown.
    latitude: f32,
    longitude: f32,
}

/// A subdivision, region or country name. There are a few hundred, shared by
/// every row.
struct Part {
    text: [Box<str>; 8],
    folded: [String; 8],
}

impl Part {
    fn new(french: &str) -> Self {
        let names = NAMES.iter().find(|names| names[0] == french);
        let name = |slot: usize| names.map_or(french, |names| names[slot]);
        Self {
            text: std::array::from_fn(|slot| name(slot).into()),
            folded: std::array::from_fn(|slot| normalize_key(name(slot))),
        }
    }
}

/// `YYYY-MM-DD` as `YYYYMMDD`, 0 when empty.
fn pack_date(date: &str) -> u32 {
    date.bytes()
        .filter(u8::is_ascii_digit)
        .fold(0, |packed, digit| packed * 10 + u32::from(digit - b'0'))
}

fn unpack_date(packed: u32) -> Option<String> {
    (packed != 0).then(|| {
        format!(
            "{:04}-{:02}-{:02}",
            packed / 10_000,
            packed / 100 % 100,
            packed % 100
        )
    })
}

struct Dictionary {
    entries: Vec<Entry>,
    text: String,
    parts: Vec<Part>,
    /// Entry indexes sorted by folded name, to find a place by its name.
    by_name: Vec<u32>,
    /// Indexes of the entries with a code, sorted by it, to find a place by
    /// its official code when a label's name is not known (a hamlet named
    /// before its municipality's code).
    by_code: Vec<u32>,
}

impl Dictionary {
    fn parse(csv: &str) -> Self {
        Self::parse_keeping(csv, |_, _| true)
    }

    /// The dictionary of the rows a label of `labels` may be located by: named
    /// like one of its parts, or bearing one of its parts as a code — every
    /// candidate [`Self::locate_all`] may weigh for them, homonyms included,
    /// so it locates them as the whole dictionary would.
    fn for_labels(csv: &str, labels: &[(&str, i64)]) -> Self {
        let mut names: HashSet<String> = HashSet::new();
        let mut codes: HashSet<String> = HashSet::new();
        for (label, _) in labels {
            for part in label.split(',').map(str::trim).filter(|p| !p.is_empty()) {
                names.insert(normalize_key(part));
                codes.insert(part.to_ascii_uppercase());
            }
        }
        Self::parse_keeping(csv, |folded, line| {
            names.contains(folded)
                || second_field(line).is_some_and(|code| {
                    !code.is_empty() && codes.contains(&code.to_ascii_uppercase())
                })
        })
    }

    /// The rows `keep` accepts, given their folded name and their line. A row
    /// it refuses is not split: only its first fields are read.
    fn parse_keeping(csv: &str, keep: impl Fn(&str, &str) -> bool) -> Self {
        let mut text = String::new();
        let mut store = |value: &str| {
            let span = Span {
                start: u32::try_from(text.len()).expect("the dictionary text fits in 4 GiB"),
                len: u32::try_from(value.len()).expect("a field fits in 4 GiB"),
            };
            text.push_str(value);
            span
        };
        let mut parts = Vec::new();
        let mut interned: HashMap<String, u16> = HashMap::new();
        let mut intern = |value: &str| -> u16 {
            *interned.entry(value.to_string()).or_insert_with(|| {
                parts.push(Part::new(value));
                u16::try_from(parts.len() - 1).expect("fewer than 65,536 place parts")
            })
        };
        let mut entries = Vec::new();
        for line in csv.lines().filter(|l| !l.is_empty()) {
            let folded = normalize_key(&first_field(line));
            if !keep(&folded, line) {
                continue;
            }
            let fields = split_quoted(line);
            let [
                name,
                code,
                subdivision,
                region,
                country,
                kind,
                from,
                until,
                successor,
                lat,
                lon,
                current,
            ] = fields.as_slice()
            else {
                panic!("the embedded place dictionary has a malformed row: {line}");
            };
            let kind = PlaceKind::parse(kind)
                .unwrap_or_else(|| panic!("unknown place kind `{kind}` in the dictionary"));
            let coordinate = |value: &str| value.parse().unwrap_or(f32::NAN);
            entries.push(Entry {
                name: store(name),
                folded: store(&folded),
                code: store(code),
                successor: store(successor),
                subdivision: intern(subdivision),
                region: intern(region),
                country: intern(country),
                kind,
                current: current == "1",
                valid_from: pack_date(from),
                valid_until: pack_date(until),
                latitude: coordinate(lat),
                longitude: coordinate(lon),
            });
        }
        text.shrink_to_fit();
        entries.shrink_to_fit();
        let mut dictionary = Self {
            entries,
            text,
            parts,
            by_name: Vec::new(),
            by_code: Vec::new(),
        };
        let mut by_name: Vec<u32> = (0..dictionary.entries.len())
            .map(|i| u32::try_from(i).expect("fewer than 4 billion places"))
            .collect();
        by_name.sort_by(|a, b| {
            let name = |i: &u32| dictionary.get(dictionary.entries[*i as usize].folded);
            name(a).cmp(name(b))
        });
        dictionary.by_name = by_name;
        let mut by_code: Vec<u32> = (0..dictionary.entries.len())
            .filter(|&i| dictionary.entries[i].code.len > 0)
            .map(|i| u32::try_from(i).expect("fewer than 4 billion places"))
            .collect();
        by_code.sort_by_cached_key(|i| {
            dictionary
                .get(dictionary.entries[*i as usize].code)
                .to_ascii_uppercase()
        });
        dictionary.by_code = by_code;
        dictionary
    }

    /// The entries whose code is `code`, ignoring ASCII case.
    fn coded(&self, code: &str) -> impl Iterator<Item = &Entry> {
        let code = code.to_ascii_uppercase();
        let key = |i: &u32| {
            self.get(self.entries[*i as usize].code)
                .to_ascii_uppercase()
        };
        let start = self.by_code.partition_point(|i| key(i) < code);
        self.by_code[start..]
            .iter()
            .take_while(move |i| key(i) == code)
            .map(|i| &self.entries[*i as usize])
    }

    /// The entries whose folded name is exactly `folded`.
    fn named(&self, folded: &str) -> impl Iterator<Item = &Entry> {
        let name = |i: &u32| self.get(self.entries[*i as usize].folded);
        let start = self.by_name.partition_point(|i| name(i) < folded);
        self.by_name[start..]
            .iter()
            .take_while(move |i| name(i) == folded)
            .map(|i| &self.entries[*i as usize])
    }

    /// Coordinates for the places of a tree, each written as the tree
    /// records it: its name, then optionally its code, subdivision, region
    /// and country, comma-separated, with how often the tree uses it.
    ///
    /// The name must match a dictionary place exactly (case and accents
    /// aside). Among homonyms, the one whose code, subdivision, region or
    /// country the label also names wins, and a bare name whose homonyms all
    /// stand in the same spot is located there. Any other bare name is read
    /// in the country the tree uses most among those where it exists, as a
    /// commune rather than a former name: "Brest" in a French tree is the
    /// one in Finistère, not the German village.
    ///
    /// A homonym read that way always has its country; its region and
    /// subdivision when all its candidates there share them.
    fn locate_all(&self, labels: &[(&str, i64)], lang: ReferenceLang) -> Vec<PlaceLocation> {
        let lang = lang.slot();
        let part = |index: u16| {
            let text = &self.parts[usize::from(index)].text[lang];
            (!text.is_empty()).then(|| text.to_string())
        };
        // The part every entry shares, if they all do.
        let shared = |entries: &[&Entry], of: fn(&Entry) -> u16| {
            let first = of(entries.first()?);
            entries
                .iter()
                .all(|e| of(e) == first)
                .then(|| part(first))?
        };
        let resolved: Vec<Located> = labels
            .iter()
            .map(|(label, _)| self.resolve(label))
            .collect();
        let mut weights: HashMap<u16, i64> = HashMap::new();
        for (found, (_, count)) in resolved.iter().zip(labels) {
            if let Located::At(entry) = found {
                *weights.entry(entry.country).or_default() += count;
            }
        }
        let mut countries: Vec<(u16, i64)> = weights.into_iter().collect();
        countries.sort_by_key(|&(country, weight)| (std::cmp::Reverse(weight), country));
        resolved
            .into_iter()
            .map(|found| match found {
                Located::At(entry) => PlaceLocation {
                    spot: Some(spot(entry)),
                    country: part(entry.country),
                    region: part(entry.region),
                    subdivision: part(entry.subdivision),
                },
                Located::Nowhere => PlaceLocation::default(),
                Located::Among(candidates) => {
                    let Some((country, _)) = countries
                        .iter()
                        .find(|(country, _)| candidates.iter().any(|e| e.country == *country))
                    else {
                        return PlaceLocation::default();
                    };
                    let local = candidates.iter().filter(|e| e.country == *country);
                    let rank = local.clone().map(|e| kind_rank(e.kind)).min();
                    let local: Vec<&Entry> = local
                        .filter(|e| Some(kind_rank(e.kind)) == rank)
                        .copied()
                        .collect();
                    PlaceLocation {
                        spot: clustered(&local),
                        country: part(*country),
                        region: shared(&local, |e| e.region),
                        subdivision: shared(&local, |e| e.subdivision),
                    }
                }
            })
            .collect()
    }

    /// What a single label says on its own: a spot, or homonyms that only
    /// the rest of the tree can tell apart.
    ///
    /// A label whose name the dictionary does not know — a hamlet, a farm, a
    /// lieu-dit written before its municipality — is located by the first of
    /// the following parts that places it: a municipality's code (INSEE, BFS…)
    /// or name, confirmed by what follows it as a name is. It is then put at
    /// its municipality's spot, which a heat map cannot tell apart.
    fn resolve(&self, label: &str) -> Located<'_> {
        let raw: Vec<&str> = label
            .split(',')
            .map(str::trim)
            .filter(|p| !normalize_key(p).is_empty())
            .collect();
        let folded: Vec<String> = raw.iter().map(|p| normalize_key(p)).collect();
        let Some(name) = folded.first() else {
            return Located::Nowhere;
        };
        let located = |e: &&Entry| !e.latitude.is_nan() && !e.longitude.is_nan();
        let candidates: Vec<&Entry> = self.named(name).filter(located).collect();
        if !candidates.is_empty() {
            return self.read(candidates, &folded[1..]);
        }
        // The name is unknown: read the label from its enclosing places. A
        // code places it on its own, homonyms aside; a name only when a part
        // after it confirms it — a municipality of the same name elsewhere in
        // the world is no place to put a hamlet.
        (1..raw.len())
            .find_map(|i| {
                let rest = &folded[i + 1..];
                let by_code: Vec<&Entry> = self.coded(raw[i]).filter(located).collect();
                if !by_code.is_empty() {
                    return match self.read(by_code, rest) {
                        Located::At(entry) => Some(Located::At(entry)),
                        _ => None,
                    };
                }
                self.named(&folded[i])
                    .filter(located)
                    .max_by_key(|e| (self.score(e, rest), e.current))
                    .filter(|e| self.score(e, rest) > 0)
                    .map(Located::At)
            })
            .unwrap_or(Located::Nowhere)
    }

    /// How many of `rest`, the folded parts written after a name, an entry
    /// answers to: its code, subdivision, region or country.
    fn score(&self, entry: &Entry, rest: &[String]) -> usize {
        rest.iter()
            .filter(|part| {
                self.get(entry.code).eq_ignore_ascii_case(part)
                    || [entry.subdivision, entry.region, entry.country]
                        .iter()
                        .any(|&i| self.parts[usize::from(i)].folded.contains(part))
            })
            .count()
    }

    /// The candidates for a name, told apart by `rest`: the folded parts
    /// written after it.
    fn read<'a>(&'a self, candidates: Vec<&'a Entry>, rest: &[String]) -> Located<'a> {
        let score = |entry: &Entry| self.score(entry, rest);
        let Some(best) = candidates
            .iter()
            .max_by_key(|e| (score(e), e.current))
            .copied()
        else {
            return Located::Nowhere;
        };
        if score(best) > 0 || clustered(&candidates).is_some() {
            Located::At(best)
        } else {
            Located::Among(candidates)
        }
    }

    fn get(&self, span: Span) -> &str {
        let start = span.start as usize;
        &self.text[start..start + span.len as usize]
    }

    fn search(&self, lang: ReferenceLang, query: &str, limit: usize) -> Vec<PlaceSuggestion> {
        let mut pieces = query.split(',');
        let name = normalize_key(pieces.next().unwrap_or_default());
        let qualifiers: Vec<String> = pieces
            .map(normalize_key)
            .filter(|q| !q.is_empty())
            .collect();
        if name.is_empty() || limit == 0 {
            return Vec::new();
        }
        let lang = lang.slot();
        let mut matches: Vec<(u8, &Entry)> = self
            .entries
            .iter()
            .filter_map(|entry| Some((name_rank(self.get(entry.folded), &name)?, entry)))
            .filter(|(_, entry)| {
                qualifiers.iter().all(|qualifier| {
                    let code = self.get(entry.code);
                    code.get(..qualifier.len())
                        .is_some_and(|head| head.eq_ignore_ascii_case(qualifier))
                        || [entry.subdivision, entry.region, entry.country]
                            .iter()
                            .any(|&part| {
                                starts_a_word(
                                    &self.parts[usize::from(part)].folded[lang],
                                    qualifier,
                                )
                            })
                })
            })
            .collect();
        matches.sort_by(|(rank_a, a), (rank_b, b)| {
            let key = |rank, entry: &Entry| {
                let name = self.get(entry.name);
                (rank, !entry.current, entry.kind, name.len(), name)
            };
            key(rank_a, a).cmp(&key(rank_b, b))
        });
        // A British locality and the civil parish of the same name read
        // alike and fill the field alike: the list offers them once.
        let mut shown = HashSet::new();
        matches
            .into_iter()
            .map(|(_, entry)| self.suggestion(entry, lang))
            .filter(|s| shown.insert((s.label.clone(), s.valid_until.clone())))
            .take(limit)
            .collect()
    }

    fn suggestion(&self, entry: &Entry, lang: usize) -> PlaceSuggestion {
        let part = |index: u16| self.parts[usize::from(index)].text[lang].to_string();
        let (name, code) = (self.get(entry.name), self.get(entry.code));
        let (subdivision, region, country) = (
            part(entry.subdivision),
            part(entry.region),
            part(entry.country),
        );
        let label = [name, code, &subdivision, &region, &country]
            .into_iter()
            .filter(|p| !p.is_empty())
            .collect::<Vec<_>>()
            .join(", ");
        let optional = |value: &str| (!value.is_empty()).then(|| value.to_string());
        let coordinate = |value: f32| (!value.is_nan()).then_some(f64::from(value));
        PlaceSuggestion {
            label,
            name: name.to_string(),
            code: optional(code),
            subdivision,
            region,
            country,
            kind: entry.kind,
            valid_from: unpack_date(entry.valid_from),
            valid_until: unpack_date(entry.valid_until),
            successor: optional(self.get(entry.successor)),
            latitude: coordinate(entry.latitude),
            longitude: coordinate(entry.longitude),
            current: entry.current,
        }
    }
}

/// 0 for the same name, 1 for a name starting with the query, 2 for a name
/// with a later word starting with it.
fn name_rank(name: &str, query: &str) -> Option<u8> {
    if name == query {
        Some(0)
    } else if name.starts_with(query) {
        Some(1)
    } else if starts_a_word(name, query) {
        Some(2)
    } else {
        None
    }
}

/// Splits a row of quoted fields, as the generator writes them.
/// The first field of a CSV row, read without splitting the rest.
fn first_field(line: &str) -> std::borrow::Cow<'_, str> {
    match line.strip_prefix('"') {
        Some(rest) => match rest.find('"') {
            // A doubled quote inside the name: the careful way.
            Some(end) if rest[end + 1..].starts_with('"') => {
                split_quoted(line).swap_remove(0).into()
            }
            Some(end) => rest[..end].into(),
            None => rest.into(),
        },
        None => line.split(',').next().unwrap_or_default().into(),
    }
}

/// The second field of a dictionary line — the code — without splitting
/// the rest of it.
fn second_field(line: &str) -> Option<std::borrow::Cow<'_, str>> {
    let mut quoted = false;
    let mut chars = line.char_indices().peekable();
    while let Some((at, c)) = chars.next() {
        match c {
            '"' if quoted && chars.peek().is_some_and(|&(_, next)| next == '"') => {
                chars.next();
            }
            '"' => quoted = !quoted,
            ',' if !quoted => return Some(first_field(&line[at + 1..])),
            _ => {}
        }
    }
    None
}

fn split_quoted(line: &str) -> Vec<String> {
    let mut fields = Vec::new();
    let mut field = String::new();
    let mut quoted = false;
    let mut chars = line.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '"' if quoted && chars.peek() == Some(&'"') => {
                field.push('"');
                chars.next();
            }
            '"' => quoted = !quoted,
            ',' if !quoted => fields.push(std::mem::take(&mut field)),
            _ => field.push(c),
        }
    }
    fields.push(field);
    fields
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A fictitious dictionary: a commune under its current and former
    /// département names, two homonyms, and a British hamlet.
    const ROWS: &str = r#""Bourg-A","99001","Département A","Région A","France","commune","","","","48.1","-1.5","1"
"Bourg-A","99001","Ancien Département A","Région A","France","commune","","","","48.1","-1.5",""
"Bourg-Ancien","99002","Département A","Région A","France","former_commune","","1960-01-01","99001","","",""
"Le Bourg-A","99003","Département B","Région A","France","commune","","","","","","1"
"Hamlet A","","Shire A","Angleterre","Royaume-Uni","settlement","","","","52.0","-1.0","1"
"#;

    fn names(suggestions: &[PlaceSuggestion]) -> Vec<(&str, &str)> {
        suggestions
            .iter()
            .map(|s| (s.name.as_str(), s.subdivision.as_str()))
            .collect()
    }

    #[test]
    fn exact_names_come_first_then_prefixes_then_later_words() {
        let dictionary = Dictionary::parse(ROWS);
        let found = dictionary.search(ReferenceLang::Fr, "bourg a", 10);
        assert_eq!(
            names(&found),
            [
                ("Bourg-A", "Département A"),
                ("Bourg-A", "Ancien Département A"),
                ("Bourg-Ancien", "Département A"),
                ("Le Bourg-A", "Département B"),
            ]
        );
    }

    #[test]
    fn a_suggestion_carries_its_label_and_its_parts() {
        let dictionary = Dictionary::parse(ROWS);
        let found = dictionary.search(ReferenceLang::Fr, "Bourg-Ancien", 1);
        assert_eq!(
            found[0],
            PlaceSuggestion {
                label: "Bourg-Ancien, 99002, Département A, Région A, France".to_string(),
                name: "Bourg-Ancien".to_string(),
                code: Some("99002".to_string()),
                subdivision: "Département A".to_string(),
                region: "Région A".to_string(),
                country: "France".to_string(),
                kind: PlaceKind::FormerCommune,
                valid_from: None,
                valid_until: Some("1960-01-01".to_string()),
                successor: Some("99001".to_string()),
                latitude: None,
                longitude: None,
                current: false,
            }
        );
    }

    #[test]
    fn parts_after_a_comma_narrow_the_list() {
        let dictionary = Dictionary::parse(ROWS);
        let found = dictionary.search(ReferenceLang::Fr, "bourg, ancien dep", 10);
        assert_eq!(names(&found), [("Bourg-A", "Ancien Département A")]);
        let found = dictionary.search(ReferenceLang::Fr, "bourg, 99003", 10);
        assert_eq!(names(&found), [("Le Bourg-A", "Département B")]);
    }

    #[test]
    fn the_interface_names_countries_in_its_language() {
        let dictionary = Dictionary::parse(ROWS);
        let found = dictionary.search(ReferenceLang::De, "hamlet, england", 10);
        assert_eq!(
            found[0].label,
            "Hamlet A, Shire A, England, Vereinigtes Königreich"
        );
        let found = dictionary.search(ReferenceLang::Pl, "bourg a", 1);
        assert_eq!(found[0].country, "Francja");
    }

    #[test]
    fn the_english_interface_names_british_nations_in_english() {
        let dictionary = Dictionary::parse(ROWS);
        let found = dictionary.search(ReferenceLang::En, "hamlet, england", 10);
        assert_eq!(found[0].label, "Hamlet A, Shire A, England, United Kingdom");
        let found = dictionary.search(ReferenceLang::Fr, "hamlet", 10);
        assert_eq!(found[0].label, "Hamlet A, Shire A, Angleterre, Royaume-Uni");
    }

    #[test]
    fn nothing_is_suggested_for_an_empty_name_or_limit() {
        let dictionary = Dictionary::parse(ROWS);
        assert!(
            dictionary
                .search(ReferenceLang::Fr, " , Région A", 10)
                .is_empty()
        );
        assert!(dictionary.search(ReferenceLang::Fr, "bourg", 0).is_empty());
        assert!(dictionary.search(ReferenceLang::Fr, "ourg", 10).is_empty());
    }

    #[test]
    fn a_label_is_located_by_its_name_and_what_follows_it() {
        let dictionary = Dictionary::parse(ROWS);
        let found = dictionary.locate_all(
            &[
                ("Bourg-A, 99001, Département A", 1),
                ("hamlet a, England", 1),
                // Located nowhere in the dictionary.
                ("Bourg-Ancien", 1),
                ("Nowhere A", 1),
            ],
            ReferenceLang::En,
        );
        assert_eq!(
            found.iter().map(|l| l.spot).collect::<Vec<_>>(),
            [
                Some((48.1_f32.into(), (-1.5_f32).into())),
                Some((52.0_f32.into(), (-1.0_f32).into())),
                None,
                None,
            ]
        );
        // The parts come in the requested language.
        assert_eq!(found[0].subdivision.as_deref(), Some("Département A"));
        assert_eq!(found[0].region.as_deref(), Some("Région A"));
        assert_eq!(found[1].region.as_deref(), Some("England"));
        assert_eq!(found[1].country.as_deref(), Some("United Kingdom"));
        assert_eq!(found[2], PlaceLocation::default());
    }

    #[test]
    fn an_unknown_place_is_located_by_the_municipality_after_it() {
        let dictionary = Dictionary::parse(ROWS);
        let bourg = Some((48.1_f32.into(), (-1.5_f32).into()));
        let found = dictionary.locate_all(
            &[
                // A hamlet, then its municipality's name and code.
                ("Hameau-X, Bourg-A, 99001, Département A, France", 1),
                // A former name the dictionary lacks, then the code.
                ("Bourg-A-Ancien-Nom, 99001, Département A", 1),
                // A municipality's name confirmed by nothing after it.
                ("Hameau-Y, Bourg-A", 1),
                // A code nobody bears.
                ("Hameau-Z, 99999, Département A", 1),
            ],
            ReferenceLang::En,
        );
        assert_eq!(found[0].spot, bourg);
        assert_eq!(found[0].subdivision.as_deref(), Some("Département A"));
        assert_eq!(found[1].spot, bourg);
        assert_eq!(found[2], PlaceLocation::default());
        assert_eq!(found[3], PlaceLocation::default());
    }

    #[test]
    fn a_bare_homonym_is_read_in_the_country_the_tree_uses_most() {
        let dictionary = Dictionary::parse(
            r#""Ville-A","99001","Département A","Région A","France","commune","","","","48.0","-4.0","1"
"Ville-A","","Département B","Région A","France","former_name","","","","44.0","1.0",""
"Ville-A","01001","Kreis A","Land A","Allemagne","commune","","","","53.0","9.0","1"
"Ville-B","99002","Département A","Région A","France","commune","","","","47.0","-1.0","1"
"Ville-C","01002","Kreis A","Land A","Allemagne","commune","","","","52.0","10.0","1"
"#,
        );
        let french = (48.0_f32.into(), (-4.0_f32).into());
        let german = (53.0_f32.into(), 9.0_f32.into());
        let located =
            |labels: &[(&str, i64)]| dictionary.locate_all(labels, ReferenceLang::En)[0].spot;
        assert_eq!(
            located(&[("Ville-A", 1), ("Ville-B", 3), ("Ville-C", 2)]),
            Some(french)
        );
        assert_eq!(
            located(&[("Ville-A", 1), ("Ville-B", 2), ("Ville-C", 3)]),
            Some(german)
        );
        // Nothing else in the tree tells the homonyms apart.
        assert_eq!(located(&[("Ville-A", 1)]), None);
        // Read in France, the living commune names its subdivision.
        let found = dictionary.locate_all(&[("Ville-A", 1), ("Ville-B", 3)], ReferenceLang::En);
        assert_eq!(found[0].country.as_deref(), Some("France"));
        assert_eq!(found[0].subdivision.as_deref(), Some("Département A"));
    }

    #[test]
    fn the_rows_of_a_trees_names_locate_them_as_the_whole_dictionary() {
        let csv = format!(
            "{ROWS}{}",
            r#""Ville-A","99001","Département A","Région A","France","commune","","","","48.0","-4.0","1"
"Ville-A","01001","Kreis A","Land A","Allemagne","commune","","","","53.0","9.0","1"
"Ville ""B""","99004","Département A","Région A","France","commune","","","","47.5","-1.5","1"
"#
        );
        let labels = [
            ("Bourg-A, 99001, Département A", 2),
            ("Hameau-X, 99001, Département A", 1),
            ("Ville-A", 1),
            ("Ville \"B\"", 1),
            ("hamlet a, England", 3),
            ("Nowhere A", 1),
        ];
        let whole = Dictionary::parse(&csv);
        let kept = Dictionary::for_labels(&csv, &labels);
        // Only the rows named like the labels, every homonym included.
        assert_eq!(kept.entries.len(), 6);
        assert_eq!(
            kept.locate_all(&labels, ReferenceLang::Fr),
            whole.locate_all(&labels, ReferenceLang::Fr)
        );
        // A bare homonym is still read in the country the tree uses most.
        assert_eq!(
            kept.locate_all(&labels, ReferenceLang::Fr)[1]
                .country
                .as_deref(),
            Some("France")
        );
    }

    #[test]
    fn a_first_field_is_read_whole() {
        assert_eq!(first_field(r#""Bourg-A","99001""#), "Bourg-A");
        assert_eq!(first_field(r#""Ville ""B""","99004""#), r#"Ville "B""#);
        assert_eq!(first_field("Plain,99001"), "Plain");
    }

    #[test]
    fn dates_survive_packing() {
        assert_eq!(
            unpack_date(pack_date("1790-01-01")).as_deref(),
            Some("1790-01-01")
        );
        assert_eq!(unpack_date(pack_date("")), None);
    }

    #[test]
    fn the_embedded_dictionary_loads() {
        // Every row must parse; a malformed one panics while loading.
        assert!(dictionary().entries.len() > 100_000);
    }

    /// The generator drops a row reading like another once folded, with the
    /// same kind, dates and successor (docs/place-dictionary.md §2).
    #[test]
    fn the_embedded_dictionary_holds_each_row_once() {
        let dictionary = dictionary();
        let mut seen = HashSet::new();
        let repeated: Vec<&str> = dictionary
            .entries
            .iter()
            .filter(|e| {
                !seen.insert((
                    dictionary.get(e.folded),
                    dictionary.get(e.code),
                    e.subdivision,
                    e.region,
                    e.country,
                    e.kind,
                    e.valid_from,
                    e.valid_until,
                    dictionary.get(e.successor),
                ))
            })
            .map(|e| dictionary.get(e.name))
            .collect();
        assert!(
            repeated.is_empty(),
            "{} repeated rows: {:?}",
            repeated.len(),
            &repeated[..repeated.len().min(20)]
        );
    }

    #[test]
    fn rows_reading_alike_are_suggested_once() {
        let dictionary = Dictionary::parse(concat!(
            "\"Village A\",\"\",\"Shire A\",\"Pays de Galles\",\"Royaume-Uni\",\"settlement\",\"\",\"\",\"\",\"\",\"\",\"\"\n",
            "\"Village A\",\"\",\"Shire A\",\"Pays de Galles\",\"Royaume-Uni\",\"parish\",\"\",\"\",\"\",\"\",\"\",\"\"\n",
            "\"Village A\",\"\",\"Shire A\",\"Pays de Galles\",\"Royaume-Uni\",\"former_name\",\"\",\"1974-04-01\",\"\",\"\",\"\",\"\"\n",
        ));
        let found = dictionary.search(ReferenceLang::En, "village a", 10);
        assert_eq!(found.len(), 2);
        assert_eq!(found[0].kind, PlaceKind::Settlement);
        assert_eq!(found[1].valid_until.as_deref(), Some("1974-04-01"));
    }
}
