//! Shared UI components.

pub mod audit_log;
pub mod charts;
pub mod confirm_dialog;
pub mod context_menu;
pub mod copy_field;
pub mod cropped_image;
pub mod date_input;
pub mod document_form;
pub mod history_diff;
pub mod homonym_picker;
pub mod image_cropper;
pub mod import_modal;
pub mod layout;
pub mod media_gallery;
pub mod media_input;
pub mod pedigree_chart;
pub mod pedigree_theme;
pub mod person_form;
pub mod person_profile;
pub mod place_input;
pub mod reference_tooltip;
pub mod search_person;
pub mod suggest_input;
pub mod topbar_search;
pub mod tree_cache;
pub mod tree_icon_sidebar;
pub mod union_form;
